### ISSUE TITLE
@style

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#242] opened 2020-12-23 13:05 UTC
## Style

- add `@style` as optional attribute to `<list>`
- keep name and scope

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
- EAC-CPF specific attribute
- analogue attribute in EAD: //emph@render

## Context

**Summary**: Used to specify a rendering style for string. It is recommended that the value conforms to W3C CSS.

**Description and Usage**: The style may occur on `<span>`. In a limited number of contexts that accommodate discursive description, `<span>` with style may be used to identify an arbitrary string that is intended to be rendered in a specific style. It is highly recommended that the value of style be expressed as a W3C CSS style to facilitate interoperability.

**Data Type**: string

## Solution documentation
Rephrasing _Summary_ and _Description and Usage_ needed?

**May occur within**:  `<list>`, `<span>`

## Example encoding
`<p><span style="font-style:bold">Header</span>extended desription of biography or history</p>`

**Comment by ailie-s** [comment] 2021-01-03 05:00
Tag Library Text:

**Summary:** Used to specify a rendering style for a string. It is recommended that the value conforms to W3C CSS.
**Description and Usage:** The `@style` attribute may occur on `<span>` and `<list>`. In a limited number of contexts that accommodate discursive description, `<span>` with `@style` may be used to identify an arbitrary string that is intended to be rendered in a specific style. `@style` may be used within `<list>` to specify the style of a list. It is highly recommended that the value of `@style` be expressed as a W3C CSS style to facilitate interoperability.
**Data Type:** token

**Comment by kerstarno** [comment] 2021-01-20 17:29
Decision to introduce `@style` to `<list>` instead of adopting `@mark` and `@numeration` from EAD (see #171). Will have to be made part of EAD during revision.

Example:
`<list style="list-style-type: symbols(cyclic '○' '●')">`

**Comment by kerstarno** [comment] 2021-01-20 17:33
Tested as part of Schema Team's schema testing:

- `@style` is an optional attribute in `<span>` and `<list>`
- It has the data type _token_

The above applies to both schemas, RNG and XSD. 

The attribute is ready. 

@ailie-s The TL draft above currently does not account yet for the recent change to also use `@style` with `<list>`.

**Comment by SJagodzinski** [comment] 2021-12-03 08:58
EAC-CPF meeting, 2 Dec 2021:

@fordmadox:
The new "style" attribute should have a type of string, not token.  CSS Style declarations can, and usually do, include meaningful whitespace characters.

**Comment by fordmadox** [comment] 2021-12-07 01:50
Just pushed a fix.  See https://github.com/SAA-SDT/eac-cpf-schema/pull/282/files.

**Comment by kerstarno** [comment] 2022-01-18 13:02
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that `@style` is of type normalizedString in both schemas and that values such as e.g. "color:blue;" or "font-family: verdana;" are validating fine.

**Closed as completed** 2022-05-29 15:09 UTC
Labels: Attribute, Tested by Schema Team
