### ISSUE TITLE
@lastDateTimeVerified

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/eac-cpf-schema#233] opened 2020-12-22 17:39 UTC
## Last Date and Time Verified

Remove the attribute @lastDateTimeVerified

Agreed in EAC-CPF, with feedback from EAD team, to remove this attribute to simplify the schema, cf [EAC-CPF August 2021 meeting](https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/meeting-minutes/2021/20210806_EAC-CPF_minutes.pdf).

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## EAD3 Reconciliation
**Summary**: Last date or last date and time the linked resource was verified. Verification may include link resolution as well as verification of the version of the linked object. Available in `<citation>`, `<relation>`, `<source>`, and `<term>`.

**Data Type**: Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

## Context
**Summary**: Last date or date and time the linked resource was verified.
**Description and Usage**: The lastDateTimeVerified may occur on `<citation>`, `<cpfRelation>`, `<functionRelation>`, `<resourceRelation>`, `<setComponent>`, or `<term>`. The value of the attribute provides the last date or last date and time when a related (or linked) object was verified. Verification may include link resolution as well as verification of the version of the linked object.
**Data Type**: Union of the XML Schema Datatypes date, gYear, gYearMonth, and dateTime. The following are all valid patterns: 2009-12-31, 2009, 2009-12, 2009-12-31T23:59:59

## Solution documentation: 

Remove from Tag Library.

**Comment by ailie-s** [comment] 2020-12-23 04:00
Tag Library Text:

**Summary:** Last date or last date and time the linked resource was verified. Verification may include link resolution as well as verification of the version of the linked object. Available in `<contactLine>`, `<reference>`, <`representation>` and `<source>`.
**Datatype:** Constrained to the following patterns: YYYY-MM-DD, YYYY-MM, YYYY, or  YYYY-MM-DDThh:mm:ss [with optional timezone offset from UTC in the form of [+|-][hh:mm], or "Z" to indicate the dateTime is UTC. No timezone implies the dateTime is UTC.]

**Comment by kerstarno** [comment] 2021-01-21 08:48
Tested as part of Schema Team's schema testing:

- `@lastDateTimeVerified` is an optional attribute in `<representation>`, `<source>`, `<reference>`, `<contactLine>` and `<setComponent>`
  - @ailie-s Depending on the decision of keeping or removing `<alternativeSet>` and its sub-elements, `<setComponent>` would need to be added to the TL draft above
- It is available with all elements that also allow for `@href` 
- Its data type is constrained to the options YYYY, YYYY-MM, YYYY-MM-DD, YYYY-MM-DDThh:mm:ss, YYYY-MM-DDThh:mm:ssZ, YYYY-MM-DDThh:mm:ss+hh:mm, YYYY-MM-DDThh:mm:ss-hh:mm 

The above applies to both schemas, RNG and XSD. 

The attribute is ready.

**Comment by kerstarno** [comment] 2021-05-28 12:43
Call for comments feedback from EAD team:

In their meeting on 21 May, the EAD team of TS-EAS discussed the attribute `@lastDateTimeVerified` and the question of whether or not this should also be enable with the other external linking attributes, i.e. the three new vocabulary attributes. In the course of the conversation, we wondered (1) if there are applications of the EAS out there, where checks on links are actually done regularly, and (2) how helpful this information is from a user's point of view in case the link is broke. E.g. if a link is not accessible anymore or gives an error message, how useful is it to know that this same link had been working three months ago?

We would hence like to suggest consider removing the attribute completely and to point to the option of `@localType` or `<localControl>` (if kept) for customisation to local/specific use cases or to the option of using attributes from any other namespace (to be checked whether there could be recommendations for other XML schemas providing such information).

**Comment by SJagodzinski** [comment] 2021-08-15 16:43
EAC-CPF team meeting, 8 Aug 2021:

Agreed to remove this attribute as it is underused and a relict of early internet days.

**Comment by fordmadox** [comment] 2021-09-03 00:21
This update is ready to be tested: https://github.com/SAA-SDT/eac-cpf-schema/commits/issue/233. 

I also went ahead and merged this with the development branch, since it was such a minor change and I had the time.  If I need to update anything later, just let me know.

**Comment by kerstarno** [comment] 2022-01-18 12:39
Re-tested with the XSD and RNG schemas available in the development branch (status of 8 January 2022).

I can confirm that neither schema includes `@lastDateTimeVerified` anymore. For none of the elements that previously allowed for the attribute (`<representation>`, `<source>`, `<reference>`, `<contactLine>` and `<setComponent>`), it is offered as an option and when trying to add the attribute to any of these elements, this results in a validation error.

**Closed as completed** 2022-05-29 15:06 UTC
Labels: Attribute, EAD3 Reconciliation, Tested by Schema Team, Comments period
